/**
 * lib/alertEngine.ts
 * 
 * STEADY Alert Management System
 * 
 * Purpose:
 * Manages alerts generated by the market loop.
 * Provides storage, retrieval, and notification capabilities.
 * 
 * Alert Types:
 * - INFO: Routine updates ("Market stable")
 * - WARNING: Requires attention ("Risk increasing")
 * - CRITICAL: Urgent but not acting ("Threshold approaching")
 * - ACTION: System took/recommends action ("Protection triggered")
 * 
 * Tone: Informative without panic
 */

export interface Alert {
  id: string;
  timestamp: number;
  type: "info" | "warning" | "critical" | "action";
  message: string;
  data?: any;
  read: boolean;
}

// ==========================================
// STORAGE (Frontend-only, in-memory)
// ==========================================

let alerts: Alert[] = [];
let alertIdCounter = 1;
const MAX_ALERTS = 50; // Keep last 50 alerts

// Alert listeners
type AlertCallback = (alert: Alert) => void;
const alertListeners: AlertCallback[] = [];

// ==========================================
// CORE FUNCTIONS
// ==========================================

/**
 * Add a new alert to the system
 */
export function addAlert(
  type: Alert["type"],
  message: string,
  data?: any
): Alert {
  const alert: Alert = {
    id: `alert-${alertIdCounter++}`,
    timestamp: Date.now(),
    type,
    message,
    data,
    read: false,
  };

  // Add to front of list (newest first)
  alerts.unshift(alert);

  // Trim if exceeds max
  if (alerts.length > MAX_ALERTS) {
    alerts = alerts.slice(0, MAX_ALERTS);
  }

  // Notify listeners
  notifyListeners(alert);

  console.log(`[AlertEngine] ${type.toUpperCase()}: ${message}`);

  return alert;
}

/**
 * Get all alerts
 */
export function getAlerts(): Alert[] {
  return [...alerts];
}

/**
 * Get unread alert count
 */
export function getUnreadCount(): number {
  return alerts.filter((a) => !a.read).length;
}

/**
 * Mark alert as read
 */
export function markAlertRead(alertId: string) {
  const alert = alerts.find((a) => a.id === alertId);
  if (alert) {
    alert.read = true;
  }
}

/**
 * Mark all alerts as read
 */
export function markAllAlertsRead() {
  alerts.forEach((a) => {
    a.read = false;
  });
}

/**
 * Clear all alerts
 */
export function clearAlerts() {
  alerts = [];
}

/**
 * Get alerts by type
 */
export function getAlertsByType(type: Alert["type"]): Alert[] {
  return alerts.filter((a) => a.type === type);
}

/**
 * Get recent alerts (last N minutes)
 */
export function getRecentAlerts(minutes: number = 5): Alert[] {
  const cutoff = Date.now() - minutes * 60 * 1000;
  return alerts.filter((a) => a.timestamp >= cutoff);
}

// ==========================================
// SUBSCRIPTION SYSTEM
// ==========================================

/**
 * Subscribe to new alerts
 * Returns unsubscribe function
 */
export function onNewAlert(callback: AlertCallback): () => void {
  alertListeners.push(callback);

  return () => {
    const index = alertListeners.indexOf(callback);
    if (index > -1) {
      alertListeners.splice(index, 1);
    }
  };
}

/**
 * Notify all listeners of new alert
 */
function notifyListeners(alert: Alert) {
  alertListeners.forEach((listener) => {
    try {
      listener(alert);
    } catch (error) {
      console.error("[AlertEngine] Listener error:", error);
    }
  });
}

// ==========================================
// UTILITY FUNCTIONS
// ==========================================

/**
 * Get alert icon emoji
 */
export function getAlertIcon(type: Alert["type"]): string {
  switch (type) {
    case "info":
      return "ℹ️";
    case "warning":
      return "⚠️";
    case "critical":
      return "🚨";
    case "action":
      return "⚡";
    default:
      return "•";
  }
}

/**
 * Get alert color class
 */
export function getAlertColor(type: Alert["type"]): string {
  switch (type) {
    case "info":
      return "text-cyan-400";
    case "warning":
      return "text-yellow-400";
    case "critical":
      return "text-red-400";
    case "action":
      return "text-green-400";
    default:
      return "text-gray-400";
  }
}

/**
 * Get alert background color class
 */
export function getAlertBgColor(type: Alert["type"]): string {
  switch (type) {
    case "info":
      return "bg-cyan-500/10 border-cyan-500/30";
    case "warning":
      return "bg-yellow-500/10 border-yellow-500/30";
    case "critical":
      return "bg-red-500/10 border-red-500/30";
    case "action":
      return "bg-green-500/10 border-green-500/30";
    default:
      return "bg-gray-500/10 border-gray-500/30";
  }
}

/**
 * Format timestamp for display
 */
export function formatAlertTime(timestamp: number): string {
  const now = Date.now();
  const diff = now - timestamp;
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);

  if (seconds < 60) return `${seconds}s ago`;
  if (minutes < 60) return `${minutes}m ago`;
  if (hours < 24) return `${hours}h ago`;

  return new Date(timestamp).toLocaleTimeString();
}
